services:
  cheshire-cat-core:
    build: .
    container_name: cat_181
    depends_on:
      - qdrant
      - mariadb
    env_file:
      - .cat
      - path: .cat.local
        required: false
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/docker-cat/static:/app/cat/static
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/plugins:/app/cat/plugins
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/docker-cat/data:/app/cat/data
      # mount the drymulator-client directory to the /drymulator-client directory in the container so it can be accessed by the cheshire-cat-core service and installed as a dependency
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/docker-cat/drymulator/drymulator-client:/drymulator-client
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    env_file:
      - .qdrant
      - path: .qdrant.local
        required: false
    ports:
      - 6333:6333
    expose:
      - 6333
    volumes:
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/docker-cat/qdrant_memory:/qdrant/storage
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .mariadb
      - path: .mariadb.local
        required: false
    volumes:
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/docker-cat/mysql:/var/lib/mysql
    restart: unless-stopped

  drymulator:
    build:
      context: ../drymulator
      dockerfile: Dockerfile
    ports:
      - 7435:8000
    env_file:
      - .drymulator
      - path: .drymulator.local
        required: false
    volumes:
      - /home/moscetti/cheshire-cat-ai/cheshire-cat-ai-tools/docker-cat/drymulator:/app
