[workspace]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "eval"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
eval = "pytest eval"

[dependencies]
python = ">=3.13.1,<3.14"
pyprojroot = ">=0.3.0,<0.4"
openai = ">=1.59.6,<2"
python-dotenv = ">=1.0.1,<2"
sqlalchemy = ">=2.0.37,<3"
urllib3 = ">=1.25.3,<2.1.0"
python-dateutil = ">=2.5.3"
pydantic = ">=2"
websocket-client = ">=1.6.1"
jupyterlab = ">=4.3.4,<5"
pytest = ">=8.3.4,<9"
websockets = ">=14.1,<15"
polars = ">=1.22.0,<2"
pandas = ">=2.3.2,<3"
pydantic-settings = ">=2.10.1,<3"
nbdev = ">=2.4.5,<3"
ipywidgets = ">=8.1.7,<9"
pyarrow = ">=21.0.0,<22"

[pypi-dependencies]
cheshire-cat-api = "*"
weave = ">=0.52.4, <0.53"
drymulator_client={path="../drymulator/drymulator-client", editable = true}
cat_tools={path=".", editable = true}
litellm = ">=1.76.0, <2"
google-auth = ">=2.40.3, <3"
google-cloud-aiplatform = ">=1.111.0, <2"
